spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    client-id: ${spring.application.name}
    properties:
        spring.json.add.type.headers: false # json serialize off
        request.timeout.ms: 20000
        retry.backoff.ms: 500
        auto:
          create.topics.enable: false
          register.schemas: false
          offset.reset: latest
        use.latest.version: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: all # 모든 replica 확인 후 응답 (유실 방지)
      properties:
        enable.idempotence: true # 중복 발행 방지
    consumer:
      group-id: loopers-default-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 200 # poll 당 최대 레코드 수
      properties:
        enable-auto-commit: false
    listener:
      ack-mode: manual
      type: batch # 배치 리스너 (max-poll-records 단위로 처리)

---
spring.config.activate.on-profile: local, test

spring:
  kafka:
    bootstrap-servers: localhost:19092
    admin:
      properties:
        bootstrap.servers: kafka:9092

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd
