POST {{commerce-api}}/api/v1/orders
Content-Type: application/json
X-USER-ID: {{identifier}}

{
  "items": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}
