package com.loopers.core.domain.event.type;

public enum EventType {
    PG_PAYMENT_FAILED,
    PAYMENT_DATA_PLATFORM_SENDING_FAILED,
    ORDER_DATA_PLATFORM_SENDING_FAILED,
    STOCK_INCREASE_FAIL,
    PAYED_ORDER_STATUS_CHANGED_FAIL,
    VIEW_PRODUCT_DETAIL,
    INCREASE_PRODUCT_VIEW_COUNT,
    PAYMENT_COMPLETED,
    INCREASE_TOTAL_SALES_COUNT,
    OUT_OF_STOCK,
    CLEAR_PRODUCT_CACHE,
    LIKE_PRODUCT,
    INCREASE_PRODUCT_LIKE_RANKING_SCORE,
    INCREASE_PRODUCT_VIEW_RANKING_SCORE
}
