server:
  base-url: ${SERVER_BASE_URL:http://localhost:8080}
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

cache:
  version:
    product: v1

kafka:
  topic:
    user-action-name: user-action-events
    product-like-name: product-like-metrics
    product-stock-name: product-stock-metrics
    product-view-name: product-view-metrics
    order-events-name: order-events
    payment-events-name: payment-events

resilience4j:
  circuitbreaker:
    instances:
      pgCircuit:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      pgRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
          - org.springframework.web.client.ResourceAccessException
        ignore-exceptions:
          - com.loopers.support.error.CoreException
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: true
      kafkaProducer:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.apache.kafka.common.errors.TimeoutException
          - org.apache.kafka.common.errors.NetworkException
        fail-after-max-attempts: true

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 6000
        logger-level: basic
      pgClient:
        connect-timeout: 1000
        read-timeout: 3000
        logger-level: full

payment:
  callback:
    url: ${server.base-url}/api/v1/payments/callback

pg:
  url: http://localhost:8082

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false